/* The following code was generated by JFlex 1.6.1 */

import java.util.regex.PatternSyntaxException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LexicalAnalyzer.flex</tt>
 */
class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int SHORTCOMMENTS = 2;
  public static final int LONGCOMMENTS = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\5\1\11\1\10\1\6\22\0\1\7\7\0\1\34"+
    "\1\35\1\12\1\36\1\31\1\37\1\0\1\13\1\4\11\3\1\32"+
    "\1\0\1\45\1\33\1\44\2\0\1\26\1\14\1\1\1\24\1\15"+
    "\1\40\1\16\1\42\1\17\2\1\1\27\1\1\1\20\1\23\1\21"+
    "\1\1\1\22\1\30\1\41\1\1\1\25\1\43\3\1\6\0\32\2"+
    "\12\0\1\11\u1fa2\0\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\2\4\2\5\1\6\1\7"+
    "\1\10\12\2\1\11\1\1\1\12\1\13\1\14\1\15"+
    "\1\16\3\2\1\17\1\20\1\6\2\21\1\6\1\22"+
    "\2\2\1\23\1\5\1\24\1\25\1\26\3\22\1\27"+
    "\3\22\1\30\1\31\2\22\1\32\1\22\1\33\2\22"+
    "\1\34\1\35\1\36\1\21\1\37\1\0\3\22\1\40"+
    "\3\22\1\41\1\42\7\22\1\43\1\22\1\44\1\22"+
    "\1\45\2\22\1\46\3\22\1\47\1\22\1\50\2\22"+
    "\1\51\3\22\1\52\3\22\1\53\1\22\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\u023a"+
    "\0\u0260\0\u0286\0\u02ac\0\u02d2\0\u02f8\0\u031e\0\u0344\0\162"+
    "\0\u036a\0\162\0\162\0\162\0\162\0\162\0\u0390\0\u03b6"+
    "\0\u03dc\0\u0402\0\u0428\0\162\0\u044e\0\u0474\0\u049a\0\u04c0"+
    "\0\u04e6\0\u050c\0\u010a\0\162\0\162\0\162\0\162\0\u0532"+
    "\0\u0558\0\u057e\0\u04c0\0\u05a4\0\u05ca\0\u05f0\0\u04c0\0\u04c0"+
    "\0\u0616\0\u063c\0\162\0\u0662\0\u04c0\0\u0688\0\u06ae\0\162"+
    "\0\162\0\162\0\162\0\162\0\u06d4\0\u06fa\0\u0720\0\u0746"+
    "\0\u04c0\0\u076c\0\u0792\0\u07b8\0\u04c0\0\u04c0\0\u07de\0\u0804"+
    "\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u04c0\0\u08e8\0\u04c0"+
    "\0\u090e\0\u04c0\0\u0934\0\u095a\0\u04c0\0\u0980\0\u09a6\0\u09cc"+
    "\0\u04c0\0\u09f2\0\u04c0\0\u0a18\0\u0a3e\0\u04c0\0\u0a64\0\u0a8a"+
    "\0\u0ab0\0\u04c0\0\u0ad6\0\u0afc\0\u0b22\0\u04c0\0\u0b48\0\u04c0"+
    "\0\u04c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\2\13"+
    "\1\4\1\14\1\15\1\16\1\17\1\5\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\2\5\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\5\1\41\1\42\1\43\5\44\1\45\1\46\1\44"+
    "\2\0\46\44\1\47\33\44\47\0\1\50\1\51\2\52"+
    "\7\0\15\50\7\0\4\50\4\0\3\6\44\0\2\7"+
    "\44\0\2\53\47\0\1\54\44\0\1\54\47\0\2\13"+
    "\50\0\1\55\44\0\1\56\1\57\33\0\1\50\1\51"+
    "\2\52\7\0\1\50\1\60\13\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\52\7\0\4\50\1\61\6\50\1\62"+
    "\1\50\7\0\4\50\3\0\1\50\1\51\2\52\7\0"+
    "\15\50\7\0\1\63\3\50\3\0\1\50\1\51\2\52"+
    "\7\0\7\50\1\64\5\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\52\7\0\6\50\1\65\6\50\7\0\4\50"+
    "\3\0\1\50\1\51\2\52\7\0\1\50\1\66\13\50"+
    "\7\0\4\50\3\0\1\50\1\51\2\52\7\0\6\50"+
    "\1\67\6\50\7\0\4\50\3\0\1\50\1\51\2\52"+
    "\7\0\7\50\1\70\5\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\52\7\0\12\50\1\71\2\50\7\0\4\50"+
    "\3\0\1\50\1\51\2\52\7\0\4\50\1\72\10\50"+
    "\7\0\4\50\35\0\1\73\13\0\1\50\1\51\2\52"+
    "\7\0\7\50\1\74\5\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\52\7\0\7\50\1\75\5\50\7\0\2\50"+
    "\1\76\1\50\3\0\1\50\1\51\2\52\7\0\15\50"+
    "\7\0\2\50\1\77\1\50\35\0\1\100\45\0\1\101"+
    "\10\0\1\102\7\0\1\103\44\0\1\103\53\0\1\104"+
    "\33\0\1\50\1\51\2\105\7\0\15\50\7\0\4\50"+
    "\3\0\4\51\7\0\15\51\7\0\4\51\3\0\1\105"+
    "\1\51\2\52\7\0\15\105\7\0\4\105\3\0\1\50"+
    "\1\51\2\105\7\0\2\50\1\106\12\50\7\0\4\50"+
    "\3\0\1\50\1\51\2\105\7\0\10\50\1\107\4\50"+
    "\7\0\4\50\3\0\1\50\1\51\2\105\7\0\14\50"+
    "\1\110\7\0\4\50\3\0\1\50\1\51\2\105\7\0"+
    "\15\50\7\0\1\50\1\111\2\50\3\0\1\50\1\51"+
    "\2\105\7\0\3\50\1\112\11\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\12\50\1\113\2\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\6\50\1\114"+
    "\6\50\7\0\4\50\3\0\1\50\1\51\2\105\7\0"+
    "\10\50\1\115\4\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\6\50\1\116\6\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\1\50\1\117\13\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\3\50\1\120"+
    "\11\50\7\0\4\50\3\0\1\105\1\51\2\105\7\0"+
    "\15\105\7\0\4\105\3\0\1\50\1\51\2\105\7\0"+
    "\3\50\1\121\11\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\3\50\1\122\1\50\1\123\7\50\7\0"+
    "\1\124\2\50\1\125\3\0\1\50\1\51\2\105\7\0"+
    "\1\50\1\126\13\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\4\50\1\127\10\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\10\50\1\130\4\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\3\50\1\131"+
    "\11\50\7\0\4\50\3\0\1\50\1\51\2\105\7\0"+
    "\4\50\1\132\10\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\13\50\1\133\1\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\4\50\1\134\10\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\15\50\7\0"+
    "\1\135\3\50\3\0\1\50\1\51\2\105\7\0\6\50"+
    "\1\136\6\50\7\0\4\50\3\0\1\50\1\51\2\105"+
    "\7\0\7\50\1\137\5\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\105\7\0\15\50\7\0\2\50\1\140\1\50"+
    "\3\0\1\50\1\51\2\105\7\0\15\50\7\0\1\50"+
    "\1\141\2\50\3\0\1\50\1\51\2\105\7\0\12\50"+
    "\1\142\2\50\7\0\4\50\3\0\1\50\1\51\2\105"+
    "\7\0\1\50\1\143\13\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\105\7\0\5\50\1\144\7\50\7\0\4\50"+
    "\3\0\1\50\1\51\2\105\7\0\7\50\1\145\5\50"+
    "\7\0\4\50\3\0\1\50\1\51\2\105\7\0\6\50"+
    "\1\146\6\50\7\0\4\50\3\0\1\50\1\51\2\105"+
    "\7\0\3\50\1\147\11\50\7\0\4\50\3\0\1\50"+
    "\1\51\2\105\7\0\1\150\14\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\6\50\1\151\6\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\2\50\1\152"+
    "\12\50\7\0\4\50\3\0\1\50\1\51\2\105\7\0"+
    "\13\50\1\153\1\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\13\50\1\154\1\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\7\50\1\155\5\50\7\0"+
    "\4\50\3\0\1\50\1\51\2\105\7\0\1\50\1\156"+
    "\13\50\7\0\4\50\3\0\1\50\1\51\2\105\7\0"+
    "\1\50\1\157\13\50\7\0\4\50\3\0\1\50\1\51"+
    "\2\105\7\0\2\50\1\160\12\50\7\0\4\50\3\0"+
    "\1\50\1\51\2\105\7\0\14\50\1\161\7\0\4\50"+
    "\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2926];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\23\1\1\11\1\1\5\11\5\1\1\11"+
    "\7\1\4\11\13\1\1\11\4\1\5\11\1\0\54\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, PatternSyntaxException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case LONGCOMMENTS: {
              throw new PatternSyntaxException("A comment is never closed.",yytext(),yyline);
            }
            case 114: break;
            default:
          { 	return new Symbol(LexicalUnit.EOS, yyline, yycolumn);
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new PatternSyntaxException("Unmatched token, out of symbols",yytext(),yyline);
            }
          case 46: break;
          case 2: 
            { return new Symbol(LexicalUnit.PROGNAME, yyline, yycolumn, yytext());
            }
          case 47: break;
          case 3: 
            { return new Symbol(LexicalUnit.VARNAME, yyline, yycolumn, yytext());
            }
          case 48: break;
          case 4: 
            { return new Symbol(LexicalUnit.NUMBER, yyline, yycolumn, Integer.valueOf(yytext()));
            }
          case 49: break;
          case 5: 
            { return new Symbol(LexicalUnit.ENDLINE, yyline, yycolumn, "\\n");
            }
          case 50: break;
          case 6: 
            { 
            }
          case 51: break;
          case 7: 
            { return new Symbol(LexicalUnit.TIMES, yyline, yycolumn, yytext());
            }
          case 52: break;
          case 8: 
            { return new Symbol(LexicalUnit.DIVIDE, yyline, yycolumn, yytext());
            }
          case 53: break;
          case 9: 
            { return new Symbol(LexicalUnit.COMMA, yyline, yycolumn, yytext());
            }
          case 54: break;
          case 10: 
            { return new Symbol(LexicalUnit.EQ, yyline, yycolumn, yytext());
            }
          case 55: break;
          case 11: 
            { return new Symbol(LexicalUnit.LPAREN, yyline, yycolumn, yytext());
            }
          case 56: break;
          case 12: 
            { return new Symbol(LexicalUnit.RPAREN, yyline, yycolumn, yytext());
            }
          case 57: break;
          case 13: 
            { return new Symbol(LexicalUnit.PLUS, yyline, yycolumn, yytext());
            }
          case 58: break;
          case 14: 
            { return new Symbol(LexicalUnit.MINUS, yyline, yycolumn, yytext());
            }
          case 59: break;
          case 15: 
            { return new Symbol(LexicalUnit.GT, yyline, yycolumn, yytext());
            }
          case 60: break;
          case 16: 
            { return new Symbol(LexicalUnit.LT, yyline, yycolumn, yytext());
            }
          case 61: break;
          case 17: 
            { yybegin(YYINITIAL); return new Symbol(LexicalUnit.ENDLINE, yyline, yycolumn, "\\n");
            }
          case 62: break;
          case 18: 
            { System.err.println("Warning! Program names in uppercase are deprecated: " + yytext()); return new Symbol(LexicalUnit.PROGNAME, yyline, yycolumn, yytext());
            }
          case 63: break;
          case 19: 
            { System.err.println("Warning! Numbers with leading zeros are deprecated: " + yytext()); return new Symbol(LexicalUnit.NUMBER, yyline, yycolumn, Integer.valueOf(yytext()));
            }
          case 64: break;
          case 20: 
            { throw new PatternSyntaxException("A comment is closed, but never opened.",yytext(),yyline);
            }
          case 65: break;
          case 21: 
            { yybegin(LONGCOMMENTS);
            }
          case 66: break;
          case 22: 
            { yybegin(SHORTCOMMENTS);
            }
          case 67: break;
          case 23: 
            { return new Symbol(LexicalUnit.IF, yyline, yycolumn, yytext());
            }
          case 68: break;
          case 24: 
            { return new Symbol(LexicalUnit.OR, yyline, yycolumn, yytext());
            }
          case 69: break;
          case 25: 
            { return new Symbol(LexicalUnit.DO, yyline, yycolumn, yytext());
            }
          case 70: break;
          case 26: 
            { return new Symbol(LexicalUnit.ASSIGN, yyline, yycolumn, yytext());
            }
          case 71: break;
          case 27: 
            { return new Symbol(LexicalUnit.TO, yyline, yycolumn, yytext());
            }
          case 72: break;
          case 28: 
            { return new Symbol(LexicalUnit.GEQ, yyline, yycolumn, yytext());
            }
          case 73: break;
          case 29: 
            { return new Symbol(LexicalUnit.LEQ, yyline, yycolumn, yytext());
            }
          case 74: break;
          case 30: 
            { return new Symbol(LexicalUnit.NEQ, yyline, yycolumn, yytext());
            }
          case 75: break;
          case 31: 
            { yybegin(YYINITIAL);
            }
          case 76: break;
          case 32: 
            { return new Symbol(LexicalUnit.NOT, yyline, yycolumn, yytext());
            }
          case 77: break;
          case 33: 
            { return new Symbol(LexicalUnit.AND, yyline, yycolumn, yytext());
            }
          case 78: break;
          case 34: 
            { return new Symbol(LexicalUnit.FOR, yyline, yycolumn, yytext());
            }
          case 79: break;
          case 35: 
            { return new Symbol(LexicalUnit.ELSE, yyline, yycolumn, yytext());
            }
          case 80: break;
          case 36: 
            { return new Symbol(LexicalUnit.READ, yyline, yycolumn, yytext());
            }
          case 81: break;
          case 37: 
            { return new Symbol(LexicalUnit.THEN, yyline, yycolumn, yytext());
            }
          case 82: break;
          case 38: 
            { return new Symbol(LexicalUnit.ENDIF, yyline, yycolumn, yytext());
            }
          case 83: break;
          case 39: 
            { return new Symbol(LexicalUnit.PRINT, yyline, yycolumn, yytext());
            }
          case 84: break;
          case 40: 
            { return new Symbol(LexicalUnit.WHILE, yyline, yycolumn, yytext());
            }
          case 85: break;
          case 41: 
            { return new Symbol(LexicalUnit.ENDFOR, yyline, yycolumn, yytext());
            }
          case 86: break;
          case 42: 
            { return new Symbol(LexicalUnit.ENDPROG, yyline, yycolumn, yytext());
            }
          case 87: break;
          case 43: 
            { return new Symbol(LexicalUnit.ENDWHILE, yyline, yycolumn, yytext());
            }
          case 88: break;
          case 44: 
            { return new Symbol(LexicalUnit.BEGINPROG, yyline, yycolumn, yytext());
            }
          case 89: break;
          case 45: 
            { return new Symbol(LexicalUnit.VARIABLES, yyline, yycolumn, yytext());
            }
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
